name: 'Comment analyzer'
description: 'Analyze and handle comments in issues, pull requests, and discussions, and perform actions in the repository based on the analysis'
author: 'CobosDS'
inputs:
  github_token:
    description: 'GitHub token'
    required: true
  server_url:
    description: 'URL of the analysis server'
    required: true
  sendinblue_api_key:
    description: 'Sendinblue API key'
    required: true
  email_from:
    description: 'Sender email address'
    required: true
  email_to:
    description: 'Recipient email address'
    required: true
  bot_user:
    description: 'Bot GitHub username'
    required: true
  bot_token:
    description: 'Bot GitHub token'
    required: true
  comment_json:
    description: 'Path to comment JSON file'
    required: true
  flags:
    description: 'Flags from the analysis'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Analyze and act on comment
      shell: bash
      run: |
        curl -X POST "${{ inputs.server_url }}" -H "Content-Type: application/json" \
             -d @${{ inputs.comment_json }} \
             -o data/comment_analysis_result.json
        cat data/comment_analysis_result.json

        classification=$(jq -r '.analysis.classification' data/comment_analysis_result.json)
        echo "Classification: $classification"

        if [ "$classification" == "positive" ]; then
          COMMENT_BODY=$(jq -r '.response_comment' data/comment_analysis_result.json)
          if [[ "${{ github.event_name }}" == "issue_comment" ]]; then
            curl -X POST -H "Authorization: token ${{ inputs.bot_token }}" \
                 -H "Accept: application/vnd.github.v3+json" \
                 https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/comments \
                 -d '{"body":"'"$COMMENT_BODY"'"}'
          elif [[ "${{ github.event_name }}" == "pull_request_review_comment" ]]; then
            curl -X POST -H "Authorization: token ${{ inputs.bot_token }}" \
                 -H "Accept: application/vnd.github.v3+json" \
                 https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/comments \
                 -d '{"body":"'"$COMMENT_BODY"'"}'
          elif [[ "${{ github.event_name }}" == "discussion_comment" ]]; then
            curl -X POST -H "Authorization: token ${{ inputs.bot_token }}" \
                 -H "Accept: application/vnd.github.v3+json" \
                 https://api.github.com/repos/${{ github.repository }}/discussions/${{ github.event.discussion.id }}/comments \
                 -d '{"body":"'"$COMMENT_BODY"'"}'
          fi
        elif [ "$classification" == "negative" ]; then
          if [[ "${{ github.event_name }}" == "issue_comment" ]]; then
            curl -X DELETE -H "Authorization: token ${{ inputs.bot_token }}" \
                 -H "Accept: application/vnd.github.v3+json" \
                 https://api.github.com/repos/${{ github.repository }}/issues/comments/${{ github.event.comment.id }}
          elif [[ "${{ github.event_name }}" == "pull_request_review_comment" ]]; then
            curl -X DELETE -H "Authorization: token ${{ inputs.bot_token }}" \
                 -H "Accept: application/vnd.github.v3+json" \
                 https://api.github.com/repos/${{ github.repository }}/pulls/comments/${{ github.event.comment.id }}
          elif [[ "${{ github.event_name }}" == "discussion_comment" ]]; then
            curl -X DELETE -H "Authorization: token ${{ inputs.bot_token }}" \
                 -H "Accept: application/vnd.github.v3+json" \
                 https://api.github.com/repos/${{ github.repository }}/discussions/comments/${{ github.event.comment.id }}
          fi
        fi

    - name: Send email notification
      shell: bash
      run: |
        classification=$(jq -r '.analysis.classification' data/comment_analysis_result.json)
        email_body=""

        if [ "$classification" == "positive" ]; then
          email_body="A positive action was taken. Details: $(cat ${{ inputs.comment_json }})"
        elif [ "$classification" == "negative" ]; then
          email_body="A negative action was taken. Details: $(cat ${{ inputs.comment_json }})"
        fi

        email_json=$(jq -n --arg from_name "GitHub Actions" \
                          --arg from_email "${{ inputs.email_from }}" \
                          --arg to_email "${{ inputs.email_to }}" \
                          --arg subject "GitHub Actions Notification" \
                          --arg htmlContent "<html><head></head><body><p>${email_body}</p></body></html>" \
                          '{sender: {name: $from_name, email: $from_email}, to: [{email: $to_email, name: "Recipient"}], subject: $subject, htmlContent: $htmlContent}')

        echo "$email_json" | curl -X POST "https://api.brevo.com/v3/smtp/email" \
          -H "accept: application/json" \
          -H "api-key: ${{ inputs.sendinblue_api_key }}" \
          -H "Content-Type: application/json" \
          -d @-
